import mongoose from "mongoose";

const couponSchema = new mongoose.Schema({
    code: { type: String, required: true, unique: true },
    discountType: { type: String, enum: ["percent", "flat"], default: "percent" },
    discountValue: { type: Number, required: true },
    minCartValue: { type: Number, default: 0 },
    maxCartValue: { type: Number, default: null },
    expiryDate: { type: Date, required: true },
    isAutoGenerated: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },
    isUsed: { type: Boolean, default: false },
    usageLimit: { type: Number, default: null },
    usedCount: { type: Number, default: 0 },
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
}, { timestamps: true });

export default mongoose.model("Coupon", couponSchema);
// import mongoose from "mongoose";

// const couponSchema = new mongoose.Schema({
//     code: { type: String, required: true, unique: true },
//     discountType: { type: String, enum: ["percent", "flat"], default: "percent" },
//     discountValue: { type: Number, required: true },
//     minCartValue: { type: Number, default: 0 },
//     expiryDate: { type: Date, required: true },
//     isAutoGenerated: { type: Boolean, default: false },
//     isUsed: { type: Boolean, default: false },
//     user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null }
// }, { timestamps: true });

// export default mongoose.model("Coupon", couponSchema);