import mongoose from "mongoose";

const couponSchema = new mongoose.Schema({
    code: { type: String, required: true, unique: true },
    discountType: { type: String, enum: ["percent", "flat"], default: "percent" },
    discountValue: { type: Number, required: true },
    minCartValue: { type: Number, default: 0 },
    expiryDate: { type: Date, required: true },
    isAutoGenerated: { type: Boolean, default: false },
    isUsed: { type: Boolean, default: false },
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null }
}, { timestamps: true });

export default mongoose.model("Coupon", couponSchema);