import Coupon from "../models/Coupon.js";
import crypto from "crypto";


const generateCode = (prefix) => {
    const random = crypto.randomBytes(3).toString("hex").toUpperCase();
    return `${prefix}${random}`;
};
// Helper to generate unique code
export const getBestCoupon = async (req, res) => {
    try {
        const subtotal = parseFloat(req.query.subtotal);
        const userId = req.query.userId;

        if (!subtotal || isNaN(subtotal) || subtotal <= 0) {
            return res.status(400).json({ message: "Valid subtotal is required" });
        }

        let tier = null;

        if (subtotal >= 7000) {
            tier = { prefix: "MEGA30-", discountValue: 30, minCartValue: 7000, label: "30% OFF" };
        } else if (subtotal >= 5000) {
            tier = { prefix: "SAVE20-", discountValue: 20, minCartValue: 5000, label: "20% OFF" };
        } else if (subtotal >= 3000) {
            tier = { prefix: "SAVE10-", discountValue: 10, minCartValue: 3000, label: "10% OFF" };
        } else {
            return res.json({
                message: `Add Rs.${(3000 - subtotal).toFixed(2)} more to unlock a coupon!`,
                coupon: null
            });
        }


        const isValidUser = userId && userId !== "null" && userId !== "undefined";

        if (isValidUser) {
            const existingCoupon = await Coupon.findOne({
                user: userId,
                discountValue: tier.discountValue,
                isUsed: false,
                expiryDate: { $gte: new Date() }
            });

            if (existingCoupon) {
                return res.json({
                    message: `🎉 You unlocked ${tier.label}! Expires in 24 hours.`,
                    coupon: existingCoupon
                });
            }
        }

        // Generate new coupon
        const code = generateCode(tier.prefix);
        const expiryDate = new Date(Date.now() + 24 * 60 * 60 * 1000);

        const newCoupon = await Coupon.create({
            code,
            discountType: "percent",
            discountValue: tier.discountValue,
            minCartValue: tier.minCartValue,
            expiryDate,
            isAutoGenerated: true,
            user: isValidUser ? userId : null
        });

        return res.json({
            message: `🎉 You unlocked ${tier.label}! Expires in 24 hours.`,
            coupon: newCoupon
        });

    } catch (error) {
        console.log("FULL ERROR:", error.message);
        return res.status(500).json({ message: error.message });
    }
};