import Coupon from "../models/Coupon.js";
import Settings from "../models/settingsModel.js";
import crypto from "crypto";

// ── Helpers ────────────────────────────────────────────────────────────────

const generateCode = (prefix) => {
    const random = crypto.randomBytes(3).toString("hex").toUpperCase();
    return `${prefix}${random}`;
};

const getOrCreateSettings = async () => {
    let settings = await Settings.findOne();
    if (!settings) settings = await Settings.create({});
    return settings;
};

// ── Public: auto-generate best coupon based on cart subtotal ───────────────

export const getBestCoupon = async (req, res) => {
    try {
        const subtotal = parseFloat(req.query.subtotal);
        const userId = req.query.userId;

        if (!subtotal || isNaN(subtotal) || subtotal <= 0) {
            return res.status(400).json({ message: "Valid subtotal is required" });
        }

        const now = new Date();

        // Fetch all active, non-expired coupons
        const coupons = await Coupon.find({
            isActive: true,
            isUsed: false,
            expiryDate: { $gte: now },
            minCartValue: { $lte: subtotal },
        });

        // Filter by maxCartValue if set
        const eligible = coupons.filter(c =>
            !c.maxCartValue || subtotal <= c.maxCartValue
        );

        if (eligible.length === 0) {
            return res.json({ message: "No coupons available.", coupon: null });
        }

        // Pick best coupon — highest discount value
        const best = eligible.sort((a, b) => b.discountValue - a.discountValue)[0];

        return res.json({
            message: `🎉 You unlocked ${best.discountValue}${best.discountType === "percent" ? "%" : " Rs"} OFF!`,
            coupon: best,
        });

    } catch (error) {
        console.error("getBestCoupon error:", error.message);
        return res.status(500).json({ message: error.message });
    }
};

// ── Admin: get all coupons ─────────────────────────────────────────────────

export const getAllCoupons = async (req, res) => {
    try {
        const coupons = await Coupon.find().sort({ createdAt: -1 });
        res.json(coupons);
    } catch (error) {
        res.status(500).json({ message: "Error fetching coupons" });
    }
};

// ── Admin: create coupon ───────────────────────────────────────────────────

export const createCoupon = async (req, res) => {
    try {
        const { code, discountType, discountValue, minCartValue, expiryDate, usageLimit } = req.body;

        if (!code || !discountValue || !expiryDate) {
            return res.status(400).json({ message: "code, discountValue and expiryDate are required" });
        }

        const existing = await Coupon.findOne({ code: code.toUpperCase() });
        if (existing) {
            return res.status(400).json({ message: "Coupon code already exists" });
        }

        const coupon = await Coupon.create({
            code: code.toUpperCase(),
            discountType: discountType || "percent",
            discountValue: Number(discountValue),
            minCartValue: Number(minCartValue) || 0,
            expiryDate: new Date(expiryDate),
            usageLimit: usageLimit ? Number(usageLimit) : null,
            usedCount: 0,
            isActive: true,
            isAutoGenerated: false,
        });

        res.status(201).json(coupon);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// ── Admin: update coupon ───────────────────────────────────────────────────

export const updateCoupon = async (req, res) => {
    try {
        const { id } = req.params;
        const updates = req.body;

        if (updates.code) updates.code = updates.code.toUpperCase();
        if (updates.discountValue !== undefined) updates.discountValue = Number(updates.discountValue);
        if (updates.minCartValue !== undefined) updates.minCartValue = Number(updates.minCartValue);
        if (updates.usageLimit !== undefined) updates.usageLimit = updates.usageLimit !== "" ? Number(updates.usageLimit) : null;

        const coupon = await Coupon.findByIdAndUpdate(id, updates, { new: true });
        if (!coupon) return res.status(404).json({ message: "Coupon not found" });

        res.json(coupon);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// ── Admin: delete coupon ───────────────────────────────────────────────────

export const deleteCoupon = async (req, res) => {
    try {
        const coupon = await Coupon.findByIdAndDelete(req.params.id);
        if (!coupon) return res.status(404).json({ message: "Coupon not found" });
        res.json({ message: "Coupon deleted" });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};
